[package]
name = "floripa-hack"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = [ "serde" ] }
serde = { version = "1.0.218", features = [ "derive" ] }
tokio = { version = "1.43.0", features = [ "full" ] }
nwc = "0.39"
